### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KarloVrbicSpeck** [hunterxxx/huawei-map-clustering#1]
What license is used to publish this code?

**Comment by hunterxxx** [comment]
No license needed, free to use.

**Comment by KarloVrbicSpeck** [comment]
What I meant to say is that if you want other people using this code you should probably add license(Apache, MIT, etc.) because no license is equal to all rights reserved.

https://softwareengineering.stackexchange.com/questions/276144/using-unlicensed-code#276147

**Comment by Zhuinden** [comment]
I guess it should be treated as the "do whatever the F you want" license? 🤔 

https://choosealicense.com/licenses/wtfpl/

**Comment by hunterxxx** [comment]
@Zhuinden I like that license :D are you using that too?

**Comment by Zhuinden** [comment]
I typically just throw [Apache License](https://choosealicense.com/licenses/apache-2.0/) on everything, no one's said anything negative about it so far as it.

Although in retrospect, maybe the [MIT license](https://choosealicense.com/licenses/mit/) would have been more applicable. 🤔 

Reading about it, I also kinda like https://choosealicense.com/licenses/unlicense/ for sample code
